## Auto Gradient

In [2]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y是作为操作的结果被创建的，所以y有grad_fn

In [5]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_(…)会改变张量的requires_grad标记,输入的标记默认为False

In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


反向传播

In [9]:
out.backward()
print(x.grad) # return partial out / partial x

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


事实上,torch.autograd是用来计算所给的某个向量v和Jacobi矩阵的积的,如果对于标量函数$z = g(\vec{y})$,如果v是z对y的梯度,则Jacobi矩阵(y对x)与v的积是z对x的梯度

Jacobi-向量积

In [4]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000: # L2 Norm
 y = y * 2
print(y)

tensor([ 414.1622, 1565.7904,  329.7014], grad_fn=<MulBackward0>)


现在在这种情况下，y 不再是一个标量,torch.autograd不能够直接计算整个雅可比，但是如果我们只想要雅可比向量积，只需要简单的传递向量给backward作为参数

In [5]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


将代码放在with torch.no_grad()块下,停止对从跟踪历史中的.requires_grad=True的张量自动求导

In [7]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
