## Tensor

In [4]:
import torch

构造矩阵，但不初始化

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[3.7826e-35, 6.0956e-43, 3.7823e-35],
        [6.0956e-43, 3.7827e-35, 6.0956e-43],
        [3.7827e-35, 6.0956e-43, 3.7826e-35],
        [6.0956e-43, 3.7826e-35, 6.0956e-43],
        [3.7826e-35, 6.0956e-43, 3.7823e-35]])


构造随机初始化矩阵

In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.2245, 0.1212, 0.4250],
        [0.2083, 0.4504, 0.8614],
        [0.9933, 0.5067, 0.1931],
        [0.7266, 0.2928, 0.7806],
        [0.1938, 0.3108, 0.6651]])


构造一个全0，数据类型是long的矩阵//

In [7]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


构造一个张量，直接使用数据

In [8]:
x = torch.tensor([1.5,2])
print(x)

tensor([1.5000, 2.0000])


创建一个基于已存在tensor的tensor

In [14]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0624, -0.0760, -0.4773],
        [-0.1440,  1.1108,  0.8583],
        [ 0.8030, -0.7521, -0.7321],
        [-0.7389, -1.3217,  0.4097],
        [ 0.3275,  0.3938,  0.0795]])


获取维度信息

In [15]:
print(x.size())
row, col = x.size() # 返回一个元组
print(f'row = {row}, col = {col}')

torch.Size([5, 3])
row = 5, col = 3


加法的两种方式

In [16]:
y = torch.rand(5,3)
print(x + y)
print(torch.add(x,y))

tensor([[ 1.2397,  0.0774, -0.0037],
        [-0.0915,  1.8356,  1.7391],
        [ 1.4990, -0.0796,  0.0361],
        [-0.1341, -0.8448,  1.2340],
        [ 1.0056,  1.0446,  0.9737]])
tensor([[ 1.2397,  0.0774, -0.0037],
        [-0.0915,  1.8356,  1.7391],
        [ 1.4990, -0.0796,  0.0361],
        [-0.1341, -0.8448,  1.2340],
        [ 1.0056,  1.0446,  0.9737]])


加法：提供一个输出tensor作为参数

In [17]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.2397,  0.0774, -0.0037],
        [-0.0915,  1.8356,  1.7391],
        [ 1.4990, -0.0796,  0.0361],
        [-0.1341, -0.8448,  1.2340],
        [ 1.0056,  1.0446,  0.9737]])


加法：in-place

In [18]:
print(y)
y.add_(x)
print(y)

tensor([[0.1773, 0.1534, 0.4736],
        [0.0525, 0.7248, 0.8808],
        [0.6960, 0.6725, 0.7682],
        [0.6048, 0.4769, 0.8242],
        [0.6781, 0.6508, 0.8942]])
tensor([[ 1.2397,  0.0774, -0.0037],
        [-0.0915,  1.8356,  1.7391],
        [ 1.4990, -0.0796,  0.0361],
        [-0.1341, -0.8448,  1.2340],
        [ 1.0056,  1.0446,  0.9737]])


索引操作

In [19]:
print(x[:,0])

tensor([ 1.0624, -0.1440,  0.8030, -0.7389,  0.3275])


改变大小：torch.view (means view from other aspects)

In [22]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个元素的tensor，使用.item()来获得这个value

In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7578])
0.757847785949707
